CREATE TABLE IF NOT EXISTS groups
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(100)                            NOT NULL,
    CONSTRAINT pk_group PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS users
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name      VARCHAR(100)                            NOT NULL,
    group_id  INT                                     NOT NULL,
    is_chosen BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS pairs
(
    user_id       BIGINT NOT NULL,
    competitor_id BIGINT NOT NULL,
    CONSTRAINT fk_user_competition FOREIGN KEY (competitor_id) REFERENCES users (id),
    CONSTRAINT fk_competitor_competition FOREIGN KEY (user_id) REFERENCES users (id)
);